version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: "Git submodules"
          command: git submodule sync && git submodule update --init

      # Restore bundle cache
      - type: cache-restore
        key: cds-website-{{ checksum "Gemfile.lock" }}

      - run:
          name: "Bundle install"
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: cds-website-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: "Build english"
          command: bundle exec jekyll build --config _config_en.yml
  test:
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    docker:
      - image: circleci/ruby
    steps:
      - run:
          name: "Git submodules"
          command: git submodule sync && git submodule update --init
      - run:
          name: "Test english"
          command: bundle install && bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external --file-ignore=/assets/lib/
  deploy:
    docker:
      - image: circleci/ruby
    steps:
      - deploy:
          name: "Deploy to S3"
          command: aws s3 sync _site s3://cds-website-dist/ --delete
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: bilingualize
