version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: "Get Git submodules"
          command: git submodule sync && git submodule update --init

      # Restore bundle cache
      - type: cache-restore
        key: cds-website-{{ checksum "Gemfile.lock" }}

      - run:
          name: "Bundle install"
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: cds-website-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: "Build english"
          command: bundle exec jekyll build --config _config_en.yml --destination ~/cds-website

      - run:
          name: "Build french"
          command: bundle exec jekyll build --config _config_fr.yml --destination ~/snc-website

      # Save full build cache
      - run:
          name: "Save SHA to a file"
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: website-{{ checksum ".circle-sha" }}
          paths:
            ~/project
            ~/cds-website
            ~/snc-website

  test:
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    docker:
      - image: circleci/ruby:2.4
    steps:
      - run:
          name: "Save SHA to a file"
          command: echo $CIRCLE_SHA1 > .circle-sha

      - restore_cache:
          keys:
            - website-{{ checksum ".circle-sha" }}

      - run:
          name: "Bundle install"
          command: bundle install --path vendor/bundle

      - run:
          name: "Test english"
          command: |
            bundle exec jekyll build --config _config_en.yml
            bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external --file-ignore=/assets/lib/

      - run:
          name: "Test French"
          command: |
            bundle exec jekyll build --config _config_fr.yml
            bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external --file-ignore=/assets/lib/

  deploy:
    docker:
      - image: circleci/python
    steps:
      - run:
          name: "PIP install awsclii"
          command: |
            pip install awscli --upgrade --user
            export PATH=~/.local/bin:$PATH
            aws --version

      - run:
          name: "Save SHA to a file"
          command: echo $CIRCLE_SHA1 > .circle-sha

      - restore_cache:
          keys:
            - website-{{ checksum ".circle-sha" }}

      - deploy:
          name: "Deploy English"
          command: |
            export PATH=~/.local/bin:$PATH
            aws s3 sync ~/cds-website s3://cds-website-dist/ --delete

      - deploy:
          name: "Deploy French"
          command: |
            export PATH=~/.local/bin:$PATH
            aws s3 sync ~/snc-website s3://snc-website-dist/ --delete

  clear_caches:
    docker:
      - image: circleci/python
    steps:
      - run:
          name: "PIP install awsclii"
          command: |
            pip install awscli --upgrade --user
            export PATH=~/.local/bin:$PATH
            aws configure set preview.cloudfront true
            aws configure set preview.create-invalidation true
            aws --version

      - run:
          name: "Invalidate English Cache"
          command: |
            export PATH=~/.local/bin:$PATH
            aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E3EIUBOL3WTOOO\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

      - run:
          name: "Invalidate French Cache"
          command: |
            export PATH=~/.local/bin:$PATH
            aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E3FI5UW2E5PBD3\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: bilingualize
      - clear_caches:
          requires:
            - build
            - test
            - deploy
